name: eye_spy_app
description: A simple I Spy game app without OpenAI feature.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+4
  path_provider: ^2.0.12

flutter:
  uses-material-design: true
  assets:
    - assets/grass.jpg
    - assets/clover.jpg
    - assets/statue.jpg
    - assets/boat.jpg